#!/bin/bash

echo 'Setting up MongoDB...'
echo ''
docker build -t my_jbdb ./db

echo ''

docker run -i -t my_jbdb

if [ ! -s ".env" ] ; then
	echo 'Creating ENV file...'
	echo ''

	cp .env-sample .env
else
	echo '.env file exists...'
	echo ''
fi

echo 'Setting up Node App...'
echo ''
docker build -t my_jbnd ./app

echo ''

docker run -i -t my_jbnd

if [ -x /usr/bin/curl ] ; then
	echo -n "Do you want to populate the database? (y/n)? "
	read answer
	if echo "$answer" | grep -iq "^y" ;then
		echo '@loading...'
		echo ''
		curl -X POST http://localhost:3000/users -d "name=John Doe&email=john.doe@gmail.com&password=johndoe"
		curl -X POST http://localhost:3000/users -d "name=Jane Doe&email=jane.doe@gmail.com&password=janedoe"
	else
		echo '@loading skipped.'
	fi

	open http://localhost:3000/users
fi

echo 'Ready ...'
exit 0;